Repository LYNDVHAR-NOBILITY/Lyndvhar, pull requests merged in 2025-03, with the labels that each got.

#10 Unfucks Roguemode
  code/game/gamemodes/roguetown/chaosmode.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/gamemodes/roguetown/roguewar.dm
  code/modules/mob/dead/new_player/new_player.dm
  roguetown.dme
Labels: enhancement, Balance

#11 Kills Arcane Potential
  modular_azurepeak/virtues/combat.dm
Labels: Balance, removal

#13 Update moth.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/roguetown.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/species_types/furry/moth.dm
Labels: removal

#3 Lyndvhar Map pt1
  .github/workflows/label_merge_conflicts.yml
  _maps/lyndvhar_city.dmm
Labels: documentation, enhancement, Mapping

#21 Garrison rebalancing 2
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/area/roguetownareas.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/roguetown/roguemachine/scomm.dm
Labels: Balance

#22 Removes some mentions of Azure Peak
  _maps/map_files/dun_manor/azure_forest.dmm
  _maps/map_files/dun_manor/dun_manor.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/fluff.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
Labels: Mapping

#23 Fixes Garrison Slots
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: Balance

#26 Renames Prince/Princess
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#28 Renames dme
  .github/workflows/ci_suite.yml
  SpacemanDMM.toml
  lyndvhar.dme
Labels: documentation

#29 The great Iconing
  code/modules/client/roundendmanifest.dm
  code/modules/mob/dead/new_player/new_player.dm
  goon/browserassets/js/browserOutput.js
  icons/RoguetownIcons/default_title.dmi
  icons/ss13_32.png
  icons/ss13_64.png
  icons/tg_32.png
Labels: Spriting

#34 The Patron Gods and Daemons of Beowricke
  code/datums/gods/faiths/divine_pantheon.dm
  code/datums/gods/faiths/inhumen_pantheon.dm
  code/datums/gods/faiths/old_god.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/gods/patrons/old_god.dm
Labels: lore

#36 Merge conflict action fix probs
  .github/workflows/label_merge_conflicts.yml
Labels: documentation

#37 Redoing inquis desc
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
Labels: Balance

#30 Adventurer changes/Ready for merge
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/noble.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  lyndvhar.dme
Labels: Balance

#38 Modernizes the Primer
  strings/rt/rp_prompt.txt
Labels: lore

#31 Racial Overhaul.
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthodoxist.dm
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/courtagent.dm
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/courtier/butler.dm
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
  code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/peasants/knavewench.dm
  code/modules/jobs/job_types/roguetown/peasants/lunatic.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
  code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm
  code/modules/jobs/job_types/roguetown/youngfolk/smith_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: bug, Balance

#33 some small changes
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
Labels: Balance

#40 Weapons First Pass
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/rogueweapon.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Balance

#41 Fix the Racial issue
  code/modules/jobs/job_types/roguetown/courtier/butler.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
  code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm
  code/modules/jobs/job_types/roguetown/youngfolk/smith_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: Balance

#42 No more Dukes, Princes and Sheriffs
  code/controllers/subsystem/rogue/treasury.dm
  code/controllers/subsystem/ticker.dm
  code/datums/special_traits/traits/traits.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/antagonists/roguetown/villain/aspirant.dm
  code/modules/antagonists/roguetown/villain/vampirelord.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/events/rogue/_rogue.dm
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/jobs.dm
  code/modules/language/roguetown/thievescant.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/roguetown/roguemachine/scomm.dm
  modular_hearthstone/code/game/objects/items/signal_horn.dm
Labels: Balance

#48 Lyndvhar map part 3
  _maps/lyndvhar_city.dmm
Labels: Mapping

#47 Slot reduction and fixes
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
Labels: Balance

#43 Armor Rebalance, First Pass
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/wrists.dm
Labels: Balance

#50 Ports for my sweetheart
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
Labels: Balance, Spriting

#49 The Weocilyn Remnants
  code/__DEFINES/migrants.dm
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/datums/migrants/migrant_waves/heartfelt wave.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/goblin/chieftain.dm
Labels: Balance, lore

#51 Stylish Gambesons Port
  code/modules/clothing/rogueclothes/armor.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/armor.dmi
Labels: Spriting

#55 The Lilac Bay + Tybalm Road
  _maps/lyndvhar_coast.dmm
Labels: Mapping

#54 Changes to Goblin.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
Labels: enhancement

#52 Ports Druid Shapeshifting
  code/datums/gods/patrons/divine_pantheon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/spells/roguetown/acolyte/dendor.dm
Labels: Balance

#58 Lets everyone to shophand and lets shunned and up in servant
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm
Labels: Balance

#53 Accuracy and Pantheon Weapons and Feature Creep, also known as "Why is rogueslop so broken?"
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/roguetownprocs.dm
Labels: enhancement, Balance, Spriting

#59 Please
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm
Labels: Balance

#60 The Rebirth of the Swamp
  _maps/lyndvhar_coast.dmm
  _maps/lyndvhar_swamp.dmm
Labels: Mapping

#61 Races
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
Labels: Balance

#63 Remakes the Vampire Mansion
  _maps/map_files/generic/CentCom.dmm
Labels: map, Mapping

#64 Mount Decapitation
  _maps/lyndvhar_decapitation.dmm
Labels: Mapping

#67 Forest
  _maps/lyndvhar_city.dm
  _maps/lyndvhar_city.json
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_coast.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_decapitation.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
  code/datums/map_config.dm
  config/maps.txt
Labels: Mapping

#66 Ports the Herald Towner Class
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
  lyndvhar.dme
Labels: Balance

#68 Wedding Dress and Pure White Bug Fix
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  icons/effects/blood64.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
Labels: Balance, Spriting

#72 Adds SCOMs, HERMES, and other things to multiple spots.
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
Labels: Mapping

#65 A bunch of various Azure Peak ports in one PR
  code/__DEFINES/traits.dm
  code/_onclick/other_mobs.dm
  code/datums/components/rotting.dm
  code/datums/particle_weathers/datum_types/rain.dm
  code/datums/stress/positive_events.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/lighting/rogue_fires.dm
  code/game/objects/shapeshift_holder.dm
  code/game/say.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  code/modules/roguetown/roguestock/stockpile.dm
  modular/code/modules/living/emote.dm
  modular_azurepeak/code/game/objects/structures/fartravel.dm
  modular_azurepeak/virtues/utility.dm
  sound/music/combat_condottiero.ogg
Labels: Balance

#73 Revert "A bunch of various Azure Peak ports in one PR"
  code/__DEFINES/traits.dm
  code/_onclick/other_mobs.dm
  code/datums/components/rotting.dm
  code/datums/particle_weathers/datum_types/rain.dm
  code/datums/stress/positive_events.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/lighting/rogue_fires.dm
  code/game/objects/shapeshift_holder.dm
  code/game/say.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  code/modules/roguetown/roguestock/stockpile.dm
  modular/code/modules/living/emote.dm
  modular_azurepeak/code/game/objects/structures/fartravel.dm
  modular_azurepeak/virtues/utility.dm
  sound/music/combat_condottiero.ogg
Labels: Balance

#74 Revert "Wedding Dress and Pure White Bug Fix"
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  icons/effects/blood64.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
Labels: Balance, Spriting

#71 This BRASSFACE has access to Alcohols, the new Drugs tab, and bulks
  code/modules/cargo/packsrogue/bulk.dm
  code/modules/cargo/packsrogue/drugs.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm
  code/modules/roguetown/roguemachine/bathmaster.dm
  lyndvhar.dme
Labels: Balance

#75 Revert "Revert "Wedding Dress and Pure White Bug Fix""
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  icons/effects/blood64.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
Labels: Balance, Spriting

#76 Revert "Revert "A bunch of various Azure Peak ports in one PR""
  code/__DEFINES/traits.dm
  code/_onclick/other_mobs.dm
  code/datums/components/rotting.dm
  code/datums/particle_weathers/datum_types/rain.dm
  code/datums/stress/positive_events.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/lighting/rogue_fires.dm
  code/game/objects/shapeshift_holder.dm
  code/game/say.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  code/modules/roguetown/roguestock/stockpile.dm
  modular/code/modules/living/emote.dm
  modular_azurepeak/code/game/objects/structures/fartravel.dm
  modular_azurepeak/virtues/utility.dm
  sound/music/combat_condottiero.ogg
Labels: Balance

#77 Forest work continued
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#78 Soilfarm and townhouses
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#79 Two minor fixes ported and a new wretch class aswell as slings
  code/datums/skills/combat.dm
  code/game/objects/items.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/items/rogueweapons/ranged/slings.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/quiver.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm
  code/modules/roguetown/roguemachine/ATM.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/ammo.dmi
  lyndvhar.dme
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  sound/combat/Ranged/sling-draw-01.ogg
  sound/combat/Ranged/sling-shot-01.ogg
  sound/foley/slingload.ogg
  sound/music/combat_poacher.ogg
Labels: Balance, Spriting

#80 Adds Two new powder drugs and Two new drinks, only available through the BRASSFACE.
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/positive_events.dm
  code/modules/cargo/packsrogue/bulk.dm
  code/modules/cargo/packsrogue/drugs.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/reagent_containers/powderspice.dm
  code/modules/roguetown/roguemachine/bathmaster.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  code/modules/roguetown/roguemachine/merchant.dm
  icons/roguetown/items/produce.dmi
  sound/music/combat_ozium.ogg
  sound/music/combat_starsugar.ogg
  sound/music/credits.txt
Labels: Spriting

#84 Ports galore
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/status_effects/status_effect.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/roguetown/garrison/gatemaster.dm
  code/modules/jobs/job_types/roguetown/other/skeleton.dm
  code/modules/jobs/job_types/roguetown/other/tester.dm
  code/modules/jobs/job_types/roguetown/peasants/beggar.dm
  code/modules/jobs/job_types/roguetown/peasants/bogprisoner.dm
  code/modules/jobs/job_types/roguetown/yeomen/alchemist.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/orphan.dm
  code/modules/mob/living/carbon/human/npc/deadite.dm
  code/modules/mob/living/carbon/human/npc/searaider.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
  code/modules/spells/roguetown/vampire.dm
  code/modules/spells/spell_types/shapeshift.dm
  code/modules/surgery/bodyparts/helpers.dm
  icons/mob/actions/roguespells.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/mob/monster/crow.dmi
  lyndvhar.dme
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/beggar.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/courier.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/destitute_scholar.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/excommunicado.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/failed_apprentice.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/goatherd.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/runner.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/the_original.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/wanted.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  sound/magic/charging.ogg
  sound/magic/chargingold2.ogg
Labels: Balance, Spriting
