Repository LYNDVHAR-NOBILITY/Lyndvhar, pull requests merged in 2025-07, with the labels that each got.

#352 Adds Graggarite Armor Set
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/cloaks.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/cloaks.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_pants.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/pants.dmi
  icons/roguetown/weapons/64.dmi
  modular_azurepeak/code/game/objects/items/ritechalk.dm
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
Labels: Spriting

#196 Galotians: Slime People.
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/roguetown.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/galotian.dm
  config/game_options.txt
  icons/mob/species/gslime_F.dmi
  icons/mob/species/gslime_M.dmi
  icons/roguetown/mob/bodies/f/fslm.dmi
  icons/roguetown/mob/bodies/m/mslm.dmi
  icons/roguetown/mob/slime_hair.dmi
  icons/roguetown/mob/slime_organs1.dmi
  icons/roguetown/mob/slime_organs3.dmi
  lyndvhar.dme
  strings/rt/names/galotian/fslm.txt
  strings/rt/names/galotian/mslm.txt
Labels: Enhancement, Balance, Lore, Spriting, TEST MERGE

#354 Adds Steels Smallsword and adds them to duelist apprentice.
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/weapons/32.dmi
  modular_azurepeak/virtues/combat.dm
Labels: Spriting

#355 Yaborys - purple tieflings
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
Labels: Enhancement

#350 Terrorbog Overhaul
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
Labels: Enhancement, Balance, Mapping, TEST MERGE
