Repository LYNDVHAR-NOBILITY/Lyndvhar, pull requests merged in 2025-06, with the labels that each got.

#279 Irregular Scout has level 2 sneaking
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: Balance

#285 Revert "Dynamic mapping library"
  .github/workflows/build_bapi.yml
  _maps/map_files/lyndvhar_city/submaps/.gitkeep
  areas.dmi
  bapi/.gitignore
  bapi/Cargo.lock
  bapi/Cargo.toml
  bapi/README.md
  bapi/src/lib.rs
  bapi/src/mapmanip/.gitignore
  bapi/src/mapmanip/core/map_to_string.rs
  bapi/src/mapmanip/core/mod.rs
  bapi/src/mapmanip/core/to_dict_map.rs
  bapi/src/mapmanip/core/to_grid_map.rs
  bapi/src/mapmanip/docs/MAPPING.md
  bapi/src/mapmanip/docs/images/mapmanip_contents.png
  bapi/src/mapmanip/docs/images/mapmanip_error.png
  bapi/src/mapmanip/docs/images/mapmanip_inplace.png
  bapi/src/mapmanip/docs/images/mapmanip_markers.png
  bapi/src/mapmanip/docs/images/mapmanip_noops1.png
  bapi/src/mapmanip/docs/images/mapmanip_noops2.png
  bapi/src/mapmanip/docs/images/mapmanip_noops3.png
  bapi/src/mapmanip/docs/images/mapmanip_noops4.png
  bapi/src/mapmanip/docs/images/mapmanip_results.png
  bapi/src/mapmanip/mod.rs
  bapi/src/mapmanip/test-in/_tiny_test_map.dmm
  bapi/src/mapmanip/test-in/extracted.dmm
  bapi/src/mapmanip/test-in/inserted.dmm
  bapi/src/mapmanip/test-out/.gitkeep
  bapi/src/mapmanip/test.rs
  bapi/src/mapmanip/tools/extract_submap.rs
  bapi/src/mapmanip/tools/insert_submap.rs
  bapi/src/mapmanip/tools/mod.rs
  code/__DEFINES/rust_bapi.dm
  code/game/objects/effects/map_effects/mapmanip.dm
  code/modules/mapping/preloader.dm
  code/modules/mapping/reader.dm
  icons/effects/map_effects_96x96.dmi
  icons/effects/mapmanip_helpers.dmi
  icons/turf/areas.dmi
  lyndvhar.dme
  tools/tgs_scripts/PreCompile.sh
Labels: TEST MERGE

#288 You can now pick Apostasy
  code/datums/gods/faiths/atheism.dm
  code/datums/gods/patrons/atheism.dm
  code/game/objects/items/rogueitems/inquisitionrelics.dm
Labels: Enhancement, Lore, TEST MERGE

#289 some.. "map edits"
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Balance, Mapping, TEST MERGE

#292 Church DLC
  code/modules/roguetown/roguecrafting/structure.dm
  icons/roguetown/misc/tallstructure.dmi
Labels: Spriting

#300 Removes Atgervi's plume on the owl helmet.
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/32x48/atgervi.dmi
Labels: Spriting

#299 SurvivalistRangerSubclass
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
Labels: Enhancement, Balance, TEST MERGE

#294 PilgrimOutlanderMerge
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/tbutcher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
Labels: Enhancement, Balance, TEST MERGE

#302 Gives all Merc jobs Steelhearted
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/blackoak.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/vaquero.dm
Labels: Balance

#303 Adds Iron plate armor
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/armor.dmi
Labels: Enhancement, Balance, Spriting

#310 Bandit Favor Cost Adjustments + Hopefully fixes GOLDFACE issues
  code/modules/cargo/packsrogue/Brigand.dm
  code/modules/cargo/packsrogue/Iconoclast.dm
  code/modules/cargo/packsrogue/Knight.dm
  code/modules/cargo/packsrogue/Sellsword.dm
  code/modules/cargo/packsrogue/armor.dm
  code/modules/roguetown/roguemachine/merchant.dm
Labels: Balance

#311 malum fucking weeps
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Balance, Removal, Mapping

#313 Adjucators no longer get holy magic
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
Labels: Balance, Lore, Removal

#312 Church Remapping
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Balance, Mapping, TEST MERGE

#316 Messers are legally knives. And adds a steel messer.
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/weapons/32.dmi
Labels: Spriting

#315 Towner Adjustments and Skills
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/tbutcher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
  code/modules/jobs/jobs.dm
Labels: Enhancement, Balance, TEST MERGE

#319 Fixes the fucking. bug head. issue
  icons/mob/sprite_accessory/snouts/snouts.dmi
Labels: Spriting

#318 Drops cav captain and cav cata to 2 climbing
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
Labels: Balance

#320 brings back moth customization options
  code/modules/client/customizer/customizers/organ/ears.dm
  code/modules/client/customizer/customizers/organ/wings.dm
Labels: Enhancement

#322 Nukes Churchlings and adds Acolytes skill variances
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
Labels: Enhancement, Balance

#323 BathHousePart1
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/structures/curtain.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguewindow.dm
  code/game/objects/structures/walldeco.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/clothing/rogueclothes/robes.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head_items.dmi
  icons/roguetown/items/keys.dmi
  icons/roguetown/misc/structure.dmi
  icons/roguetown/misc/tallstructure.dmi
  icons/turf/roguefloor.dmi
Labels: Spriting

#324 Blacksmithing Quarter remap
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Enhancement, Balance, Mapping, TEST MERGE

#325 Bandit Favor House Cleaning, Readds Hedge Knight, Adds a few options to certain banditos.
  code/modules/cargo/packsrogue/Brigand.dm
  code/modules/cargo/packsrogue/Knave.dm
  code/modules/cargo/packsrogue/Knight.dm
  code/modules/cargo/packsrogue/Sellsword.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  lyndvhar.dme
Labels: Balance

#328 Hedgeknight the hedgecutter
  code/modules/cargo/packsrogue/Knight.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
Labels: Balance

#327 Adds Greathammers
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  icons/roguetown/weapons/64.dmi
Labels: Spriting

#329 BathHousePart2
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Enhancement, Balance, Mapping

#332 Statpack balancjak
  modular_azurepeak/statpacks/agile.dm
  modular_azurepeak/statpacks/physical.dm
Labels: Balance

#337 A Snowy PR PART 1
  _maps/lyndvhar_city.json
  code/__DEFINES/_tick.dm
  code/__DEFINES/components.dm
  code/__DEFINES/configuration.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
  code/__DEFINES/elements.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/particle_weather.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/turf_flags.dm
  code/__HELPERS/filters.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/particle_weather.dm
  code/controllers/subsystem/particle_weather_outdoors.dm
  code/controllers/subsystem/processing/slow_objects.dm
  code/datums/components/_component.dm
  code/datums/elements/_element.dm
  code/datums/elements/mob_overlay_effect.dm
  code/datums/outdoor_datum.dm
  code/datums/particle_weathers/_base.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/falling_leaves.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/roguetown/newtree.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/water.dm
  code/game/turfs/turf.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/roguetown/roguejobs/gravedigger/tools.dm
  icons/effects/icon_cutter.dmi
  icons/effects/particles/particle.dmi
  icons/effects/snow.dmi
  icons/roguetown/misc/foliage.dmi
  icons/roguetown/misc/foliagetall.dmi
  icons/roguetown/misc/tree.dmi
  icons/turf/roguefloor.dmi
  lyndvhar.dme
Labels: Mapping, Spriting

#336 Adds a tail
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/mob/dead/new_player/sprite_accessory/tails.dm
  icons/mob/sprite_accessory/tails/tails.dmi
Labels: Spriting

#338 Revert "A Snowy PR PART 1"
  _maps/lyndvhar_city.json
  code/__DEFINES/_tick.dm
  code/__DEFINES/components.dm
  code/__DEFINES/configuration.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
  code/__DEFINES/elements.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/particle_weather.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/turf_flags.dm
  code/__HELPERS/filters.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/particle_weather.dm
  code/controllers/subsystem/particle_weather_outdoors.dm
  code/controllers/subsystem/processing/slow_objects.dm
  code/datums/components/_component.dm
  code/datums/elements/_element.dm
  code/datums/elements/mob_overlay_effect.dm
  code/datums/outdoor_datum.dm
  code/datums/particle_weathers/_base.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/falling_leaves.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/roguetown/newtree.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/water.dm
  code/game/turfs/turf.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/roguetown/roguejobs/gravedigger/tools.dm
  icons/effects/icon_cutter.dmi
  icons/effects/particles/particle.dmi
  icons/effects/snow.dmi
  icons/roguetown/misc/foliage.dmi
  icons/roguetown/misc/foliagetall.dmi
  icons/roguetown/misc/tree.dmi
  icons/turf/roguefloor.dmi
  lyndvhar.dme
Labels: TEST MERGE

#341 Spellblade and spellsinger minor sp buff
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/spells/spell_defines.dm
  lyndvhar.dme
  modular_hearthstone/code/modules/spells/roguetown/components/enchanted_weapon.dm
  modular_hearthstone/code/modules/spells/roguetown/spells/enchanted_weapon.dm
Labels: Balance

#342 Reclasses Forvhepial sharpshooter into a Javelin Thrower
  code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm
Labels: Balance

#326 Merchant annhilation
  code/controllers/subsystem/rogue/treasury.dm
  code/modules/cargo/packsrogue/armor.dm
  code/modules/cargo/packsrogue/weapons.dm
  code/modules/roguetown/roguemachine/merchant.dm
  code/modules/roguetown/roguemachine/steward.dm
Labels: Balance

#343 Spellblade touches
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
Labels: Balance

#344 Outlander Spell Points rebracketed
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
Labels: Balance

#345 Adventurer adjustment number 500000
  code/modules/jobs/job_types/roguetown/Inquisition/inquisitor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydonianmonk.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/nobility/marshal.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/mob/mob_helpers.dm
Labels: Balance, Removal
