Repository LYNDVHAR-NOBILITY/Lyndvhar, pull requests merged in 2025-04, with the labels that each got.

#86 garrison map
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#87 garrison... keep... grass..
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#88 smokedmeat1
  icons/roguetown/topadd/Aria/Smoked_Meat1.dmi
Labels: Spriting

#89 AriaMappingCemeteryStewardry
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#90 THE MEAT PR#1
  code/game/objects/structures/hangingmeat.dm
  icons/roguetown/topadd/Aria/Smoked_Meat1.dmi
Labels: Spriting

#91 Filling in Empty Spaces pt1
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#92 AriaMappingPart10billion
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#94 IARAMAPFIXES1
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#95 ARIAFINALMAPPINGPARTMAYBE
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#96 Forest work 3
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#98 AriaMappingFixes2
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#99 AriaMappingFixes3
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#100 Aria decoration pr1
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/game/objects/structures/fancycarpet.dm
  code/game/objects/structures/hangingmeat.dm
  code/game/objects/structures/walldeco.dm
  icons/roguetown/misc/decoration.dmi
  icons/roguetown/misc/tallstructure.dmi
  icons/turf/floors/fancycarpet_1.dmi
  lyndvhar.dme
Labels: Mapping, Spriting

#101 Building Updates + Less Lighting + Roof Edits
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#102 AriaMappingFixes4
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#103 AriaMappingFixes5
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#105 Adds an admin toggle for OOC
  code/__HELPERS/config.dm
  code/controllers/globals.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/toggle_looc.dm
  modular_hearthstone/code/interface/LOOC.dm
Labels: enhancement

#106 PR
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#109 Map Tweaks
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#115 Terrorbog fixes
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
Labels: Mapping

#119 AriaMappingFixes8
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#120 Fixes bandit slots, adjusts chances for antags
  code/game/gamemodes/roguetown/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
Labels: Balance

#121 AriaPort1
  code/_onclick/hud/ghost.dm
  code/_onclick/other_mobs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/grabbing.dm
  icons/mob/screen_ghost.dmi
  icons/roguetown/mob/misc.dmi
Labels: Spriting

#124 Update villager.dm
  code/modules/jobs/job_types/roguetown/adventurer/villager.dm
Labels: Balance

#125 ManorDoorFix
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#138 Adds exotic silks and concubine servant class
  code/__DEFINES/roguetown.dm
  code/modules/cargo/packsrogue/wardrobe.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/clothing/rogueclothes/storage.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  icons/roguetown/clothing/belts.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/onmob/belts.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
  modular_azurepeak/code/datums/loadout.dm
Labels: Balance, Spriting

#140 Ports scissors and hair dye
  code/game/objects/items/rogueitems/hair_dye.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/modules/cargo/packsrogue/apparel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/roguetown/roguecrafting/items.dm
  lyndvhar.dme
Labels: Balance

#141 AriaPort5
  code/game/objects/items.dm
  code/game/objects/items/rogueitems/leash.dm
  code/game/objects/items/rogueitems/util.dm
  code/modules/cargo/packsrogue/Things.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  icons/roguetown/clothing/neck.dmi
  lyndvhar.dme
  modular/icons/mob/collars_leashes.dmi
  modular/icons/obj/items/leashes_collars.dmi
  sound/items/collarbell1.ogg
  sound/items/collarbell2.ogg
  sound/items/collarbell3.ogg
  sound/items/collarbell4.ogg
Labels: Spriting

#144 POOR FUCKING INFANTRY GARRISON
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
Labels: Balance, Mapping

#146 Revert "POOR FUCKING INFANTRY GARRISON"
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
Labels: Balance, Mapping

#145 Random shit I did(BUT FIXED (I hope) THIS TIME)
  code/datums/components/storage/storage_types.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/ranged/crossbows.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/thug.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/vaquero.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
Labels: Balance, Spriting

#147 Fixes
  code/datums/components/storage/storage_types.dm
  code/game/objects/items/rogueweapons/ranged/bows.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Balance

#139 Adds Wretches (Needs Rebalancing)
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/dead.dm
  lyndvhar.dme
  sound/music/combat_berserker.ogg
Labels: Balance, Mapping

#150 Sewer Additions
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#153 AriaMappingFixes9
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#159 Extra exterior additions to the village
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#162 Wretch Spawn
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#164 The individual known as "another an mouse" on my Discord owes me a rabbit family.
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#163 Fixes Rapier Sprite not showing up.
  code/game/objects/items/rogueweapons/melee/swords.dm
  icons/roguetown/weapons/32.dmi
Labels: Spriting

#165 barkeeper spawn fix
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#152 Mage-related Ports
  code/__DEFINES/lighting.dm
  code/__DEFINES/traits.dm
  code/datums/mind.dm
  code/datums/mindlink.dm
  code/datums/skills/magic.dm
  code/datums/sleep_adv/sleep_adv.dm
  code/game/objects/items/granters.dm
  code/game/objects/structures/mirror.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/roguetown/villain/lich.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/other/deathknight.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/spells/roguetown/acolyte/noc.dm
  code/modules/spells/roguetown/helper.dm
  code/modules/spells/roguetown/wizard.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/lichdom.dm
  code/modules/spells/spell_types/summonitem.dm
  lyndvhar.dme
  modular_azurepeak/code/datums/mind.dm
  modular_azurepeak/code/game/objects/items/spellbooks.dm
  modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/failed_apprentice.dm
  modular_azurepeak/code/modules/spells/orison.dm
  modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm
  modular_azurepeak/virtues/combat.dm
  modular_hearthstone/code/modules/spells/roguetown/spelllist.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  sound/magic/blink.ogg
  sound/magic/shadowstep.ogg
  sound/magic/shadowstep_destination.ogg
Labels: Balance

#157 Ports Galore for my Sweetheart
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/status_effects/neutral.dm
  code/game/objects/items/rogueitems/natural/feather.dm
  code/game/objects/items/rogueitems/ropechainbola.dm
  code/game/objects/items/rogueweapons/rmb_intents.dm
  code/game/objects/shapeshift_holder.dm
  code/modules/client/customizer/customizers/bodypart_feature/hair.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/mob/dead/new_player/sprite_accessory/hair.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
  code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mossback.dm
  code/modules/mob/living/simple_animal/rogue/creacher/mudcrab.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/engineer/gadgets.dm
  code/modules/roguetown/roguemachine/mail.dm
  code/modules/spells/roguetown/acolyte/dendor.dm
  code/modules/spells/spell_types/shapeshift.dm
  icons/mob/screen_alert.dmi
  icons/mob/sprite_accessory/hair/human_hair.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_shirts_gown.dmi
  icons/roguetown/clothing/onmob/shirts_gown.dmi
  icons/roguetown/clothing/shirts_gown.dmi
  sound/foley/footsteps/armor/coatplates (1).ogg
  sound/foley/footsteps/armor/coatplates (2).ogg
  sound/foley/footsteps/armor/coatplates (3).ogg
  sound/foley/footsteps/armor/plate (1).ogg
  sound/foley/footsteps/armor/plate (2).ogg
  sound/foley/footsteps/armor/plate (3).ogg
  sound/misc/mail.ogg
Labels: Balance, Spriting

#166 Inquisitor Part 1
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items/rogueitems/inquisitionrelics.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/flail.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  icons/mob/inhands/items_righthand.dmi
  icons/mob/roguehud.dmi
  icons/mob/screen_alert.dmi
  icons/roguetown/items/lighting.dmi
  icons/roguetown/weapons/32.dmi
  sound/items/censer_off.ogg
  sound/items/censer_on.ogg
  sound/magic/censercharging.ogg
Labels: Balance, Spriting

#167 Druid Grove + Map Edits
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#174 More sewer
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#175 Slashes Adventurers in half and renames them
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
Labels: Balance

#176 Makes the Forest slightly easier to navigate from start to town
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Mapping

#173 Lets the Jester's Outfit colors be changed + Mattios Boots + New Helmets (Preferably having IconDiff Bot)
  code/modules/clothing/clothing.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
Labels: Spriting

#179 Update butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
Labels: Balance
