Repository LYNDVHAR-NOBILITY/Lyndvhar, pull requests merged in 2025-05, with the labels that each got.

#169 Tipped Knives and Leash fixes
  code/datums/elements/tipped_items.dm
  code/datums/sexcon/sex_actions/deviant/facesitting.dm
  code/datums/sexcon/sex_actions/deviant/footjob.dm
  code/datums/sexcon/sex_actions/deviant/force_thighjob.dm
  code/datums/sexcon/sex_actions/deviant/frotting.dm
  code/datums/sexcon/sex_actions/deviant/scissoring.dm
  code/datums/sexcon/sex_actions/deviant/thighjob.dm
  code/datums/sexcon/sex_actions/deviant/titjob.dm
  code/datums/sexcon/sex_actions/deviant/tonguebath.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_anus.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_breasts.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_other_anus.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_other_breasts.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_other_penis.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_other_vagina.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_other_vagina_finger.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_penis.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_vagina.dm
  code/datums/sexcon/sex_actions/masturbate/masturbate_vagina_finger.dm
  code/datums/sexcon/sex_actions/oral/crotch_nuzzle.dm
  code/datums/sexcon/sex_actions/oral/kissing.dm
  code/datums/sexcon/sex_actions/oral/rimming.dm
  code/datums/sexcon/sex_actions/oral/suck_balls.dm
  code/datums/sexcon/sex_actions/oral/suck_nipples.dm
  code/datums/sexcon/sex_actions/sex/anal_ride_sex.dm
  code/datums/sexcon/sex_actions/sex/anal_sex.dm
  code/datums/sexcon/sex_actions/sex/throat_sex.dm
  code/datums/sexcon/sex_actions/sex/vaginal_ride_sex.dm
  code/datums/sexcon/sex_actions/sex/vaginal_sex.dm
  code/datums/sexcon/sex_actions/toy/toy_anal.dm
  code/datums/sexcon/sex_actions/toy/toy_other_anal.dm
  code/datums/sexcon/sex_actions/toy/toy_other_vaginal.dm
  code/datums/sexcon/sex_actions/toy/toy_vaginal.dm
  code/game/objects/items/rogueitems/leash.dm
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/roguetown/roguecrafting/items.dm
  lyndvhar.dme
  modular_azurepeak/code/datums/loadout.dm
Labels: Balance, Test Merge

#185 Misc changes...
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguecrafting/turfs.dm
  sound/music/hand2.ogg
  sound/music/viscount.ogg
Labels: Balance

#182 Something Something Templar Sprites
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
Labels: Balance, Spriting

#188 Replaces all mentions of Otava and Gronn from the code + Adventurers/Outlanders fix
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/cargo/packsrogue/alcohols.dm
  code/modules/cargo/packsrogue/bulk.dm
  code/modules/client/customizer/customizers/bodypart_feature/hair.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/jobs/job_types/roguetown/Inquisition/inquisitor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/trader.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/vaquero.dm
  code/modules/mob/dead/new_player/sprite_accessory/hair.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguemachine/steward.dm
  sound/music/combat_rhaenvalian.ogg
Labels: Balance, Mapping

#189 All this does is fix a bug
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Balance

#187 Inquisitor Part 2 (Needs TM)
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/rogueitems/inquisitionrelics.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/sister.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthodoxist.dm
  code/modules/spells/roguetown/confessor.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  lyndvhar.dme
  sound/magic/fadingpresence.ogg
  sound/magic/psywhisper.ogg
Labels: Balance, Spriting

#191 Domain Expansion: Miyazaki Swamp
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
Labels: Mapping

#192 The big PQ lessening
  code/modules/jobs/job_types/roguetown/Inquisition/inquisitor.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/sister.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
  code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/marshal.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/peasants/knavewench.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: Balance, Test Merge

#194 AriaMappingPart7
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#193 Lecherine/Leech Repellent
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  goon/browserassets/css/browserOutput.css
Labels: Balance, Test Merge

#186 AriaPort6
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/hoplite.dm
  config/admins.txt
  icons/effects/blood64x64.dmi
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  icons/roguetown/clothing/onmob/wrists.dmi
  icons/roguetown/clothing/wrists.dmi
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
  lyndvhar.dme
Labels: Balance, lore, Spriting, Test Merge

#199 AriaPort8
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  icons/roguetown/clothing/special/captain.dmi
  icons/roguetown/clothing/special/hand.dmi
  icons/roguetown/clothing/special/onmob/captain.dmi
  icons/roguetown/clothing/special/onmob/hand.dmi
Labels: Balance, Spriting

#205 Orthodoxist Warrior Monk Subclass
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/monk.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  icons/roguetown/weapons/32.dmi
Labels: Balance, Spriting, Test Merge

#211 Orthodoxist Monk Subclass Fixes
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydonianmonk.dm
  lyndvhar.dme
Labels: Balance

#208 Dark Elf Cultural Awareness PR
  code/game/objects/items/rogueweapons/melee/knives.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/game/objects/items/rogueweapons/melee/whip.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  icons/roguetown/weapons/32.dmi
  lyndvhar.dme
  sound/music/combat_delf.ogg
Labels: Balance, Spriting

#213 Anthraxi Hotfix
  code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm
Labels: Balance

#198 AriaPort7
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/roguetown/roguecrafting/weaving.dm
  config/admins.txt
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
Labels: Spriting

#214 AriaPort9
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/blackoak.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  modular_azurepeak/code/datums/loadout.dm
Labels: Balance, Spriting

#216 Ports carafes from Vanderlin and also maps some in
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/modules/reagents/reagent_containers/carafe.dm
  icons/obj/reagentfillings.dmi
  icons/roguetown/items/cooking.dmi
  lyndvhar.dme
Labels: Mapping, Spriting

#212 Changes a bunch of roles to be only Ten pantheon
  code/modules/jobs/job_types/roguetown/courtier/butler.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/marshal.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
Labels: Balance, Test Merge

#217 fixes the floating carafe I accidentally misplaced
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#219 remove my beloved Skyrim lobby screen
  icons/RoguetownIcons/default_title.dmi
  icons/RoguetownIcons/testing_title.dmi
Labels: Spriting

#220 Anthraxi lore update
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/anthrax.dm
Labels: Balance

#171 Poor Fucking Infantry 2
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/townguard.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
Labels: Balance, Removal, Mapping, TEST MERGE

#201 Boats, chairs and beds
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/vehicles/boat.dm
  lyndvhar.dme
Labels: Enhancement, TEST MERGE

#223 WardenFixes2
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
Labels: Balance

#206 Updates Forest Fort
  _maps/map_files/lyndvhar_city/lyndvhar_forest.dmm
Labels: Enhancement, Mapping, TEST MERGE

#224 Gives barbarian Another weapon option on spawn
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Enhancement, Balance, TEST MERGE

#227 The Plattering (adding in platters because i forgor and doing some city tweaks)
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#225 lets graggarites drink blood from players without puking
  code/modules/mob/living/grabbing.dm
Labels: Enhancement, TEST MERGE

#226 Ports Azures better pixelshifting
  code/__DEFINES/flags.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/living.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/turfs/closed/_closed.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/pixel_shift/pixel_shifting.dm
  lyndvhar.dme
Labels: Enhancement, TEST MERGE

#229 Update captain.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
Labels: Balance

#228 Editing the bandit camp
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/structures/fluff.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
Labels: Enhancement, Mapping, TEST MERGE

#232 Replaces the "Path of the War Scholar" book chain with unique books
  code/game/objects/items/rogueitems/books.dm
  strings/books/naledi1.json
  strings/books/naledi2.json
  strings/books/naledi3.json
  strings/books/naledi4.json
Labels: Enhancement, Lore, TEST MERGE

#236 TGM Formatting for lyndvhar_city and other map edits
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Balance, Mapping

#237 GIGA MAP FORMATTING
  _maps/map_files/lyndvhar_city/lyndvhar_coast.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_decapitation.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_swamp.dmm
Labels: Mapping

#230 Zad Mercenary Subclass
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
Labels: Enhancement, Balance, Spriting, TEST MERGE

#239 Eliminates being very faithful
  modular_azurepeak/virtues/combat.dm
Labels: Balance, TEST MERGE

#241 Xenophobia Rebalancing and other adjustments
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/courtagent.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/knavewench.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm
  code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
  code/modules/jobs/job_types/roguetown/youngfolk/smith_apprentice.dm
  code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
  sound/music/combat_swashbuckler.ogg
  sound/music/combat_swashbuckler2.ogg
Labels: Enhancement, Balance, TEST MERGE

#243 Church Gear Adjustment
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/church/acolyte.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Balance, TEST MERGE

#242 separates emotes from humens and furries
  code/modules/mob/living/carbon/human/species_types/furry/akula.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
  code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
  code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
  code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
  code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
  code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
  code/modules/mob/living/carbon/human/voicepacks/genfemale.dm
  code/modules/mob/living/carbon/human/voicepacks/genmale.dm
  code/modules/mob/living/emote.dm
  sound/vo/fsnap1.ogg
  sound/vo/fsnap2.ogg
  sound/vo/fsnap3.ogg
  sound/vo/mobs/bird/hoot.ogg
  sound/vo/mobs/bird/peep.ogg
  sound/vo/mobs/cat/cat_meow4.ogg
  sound/vo/mobs/hyena/cackle.ogg
  sound/vo/mobs/mouse/squeak.ogg
  sound/vo/mobs/possum/phiss.ogg
  sound/vo/mobs/snake/hiss.ogg
  sound/vo/mobs/vw/whine.ogg
  sound/vo/mobs/wwolf/ehowl1.ogg
  sound/vo/mobs/wwolf/ehowl2.ogg
  sound/vo/mobs/wwolf/ehowl3.ogg
  sound/vo/mobs/wwolf/ehowl4.ogg
  sound/vo/mobs/wwolf/ehowl5.ogg
Labels: Enhancement, TEST MERGE

#244 Outlander Gear and Skill Adjustments
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/hoplite.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/trader.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
Labels: Balance, TEST MERGE

#245 Noble Retinue of the Viscount
  _maps/map_files/dun_manor/dun_manor.dmm
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/game/gamemodes/objective_items.dm
  code/game/gamemodes/roguetown/chaosmode.dm
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
  code/modules/jobs/job_types/roguetown/nobility/marshal.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/roguetown/roguemachine/scomm.dm
  modular_hearthstone/code/game/objects/items/signal_horn.dm
Labels: Balance, Mapping, TEST MERGE

#246 Changes the name of the Bathhouse Attendant
  code/__DEFINES/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/jobs.dm
  code/modules/roguetown/roguemachine/bathmaster.dm
Labels: Balance, Mapping, TEST MERGE

#247 fixes the priests stole
  icons/roguetown/clothing/onmob/cloaks.dmi
Labels: Spriting

#248 fixes the bandit poster examine
  code/__DEFINES/traits.dm
  code/game/objects/structures/walldeco.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Balance

#250 Revert "Re-enables the bandit wave (one of them, atleast)"
  code/datums/migrants/migrant_wave.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
Labels: Balance, TEST MERGE

#222 2 AM Combat Dev [TESTMERGE FIRST]
  code/__HELPERS/unsorted.dm
  code/_onclick/drag_drop.dm
  code/_onclick/other_mobs.dm
  code/game/objects/items/rogueweapons/intents.dm
  code/game/objects/items/rogueweapons/melee/axes.dm
  code/game/turfs/closed/_closed.dm
  code/game/world.dm
  code/modules/admin/blacklist.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/grabbing.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/mob/living/stats.dm
  code/modules/surgery/surgery_helpers.dm
Labels: Enhancement, Balance, TEST MERGE

#258 Butcher fix
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
  lyndvhar.dme
Labels: Balance

#261 VeteranTweaks2
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
Labels: Balance, Mapping

#262 Like 5 pr ports
  code/__DEFINES/traits.dm
  code/__HELPERS/lordcolor.dm
  code/_globalvars/traits.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/rogueweapons/integrity.dm
  code/game/objects/items/rogueweapons/shields.dm
  code/game/objects/structures/mannequin.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/feet.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/structure.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  code/modules/spells/roguetown/acolyte/ravox.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/obj/mannequin.dmi
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_pants.dmi
  icons/roguetown/clothing/onmob/neck.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/pants.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/items/ore.dmi
  icons/roguetown/misc/rituals.dmi
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/heater_heraldry.dmi
  icons/roguetown/weapons/shield_heraldry.dmi
  icons/roguetown/weapons/wood_heraldry.dmi
  lyndvhar.dme
  modular_azurepeak/code/game/objects/items/ritechalk.dm
  modular_azurepeak/code/game/objects/items/ritualcircles.dm
  modular_azurepeak/code/modules/spells/pantheon/inhumen/baotha.dm
  modular_azurepeak/code/modules/spells/pantheon/inhumen/graggar.dm
Labels: Balance, Spriting

#263 VeteranHouseFix
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
Labels: Mapping

#264 This adds deadite ambushes to serveral areas
  code/game/area/roguetownareas.dm
  code/modules/antagonists/roguetown/villain/zombie/zombie.dm
  code/modules/mob/living/carbon/human/npc/deadite.dm
Labels: Enhancement, Balance, TEST MERGE

#256 Adds High Imperial (Latinate) and Zybantu (Arabic) accents
  code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm
  modular_hearthstone/code/datums/accents.dm
  strings/arabic_replacement.json
  strings/latin_replacement.json
Labels: Enhancement, TEST MERGE

#268 Updates the roundstart law defaults
  strings/laws_of_the_land.json
Labels: Enhancement, Lore, TEST MERGE

#270 Intentional surgery failures tell you to swap to weak intent.
  code/modules/surgery/_surgery_step.dm
Labels: Enhancement

#274 SmallFixes1
  _maps/map_files/lyndvhar_city/lyndvhar_city.dmm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
  modular_azurepeak/code/datums/loadout.dm
Labels: Balance, Mapping
